name: 📚 Documentation
title: "[DOCS] <my_title>"
description: Report an issue related to the documentation.
labels: ["documentation"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: |
        Thank you for your contribution to improving the documentation
        感謝您為改進文檔所做出的貢獻。
        
        If you are not sure whether you understand correctly, please use GitHub Discussions to ask for help with your issue.
        如果您不確定是否對文檔做出正確理解，請使用 GitHub 討論區尋求協助。
        
        Before submitting a contribution, please read the following instructions.
        提交改進文檔前，請遵守以下說明。
        
        - I added a very descriptive title to this issue.
          標題具有描述性。
        - I confirm that the main(or master) branch has not been updated yet.
          已確認主分支尚未更新。
      options:
        - label: Confirm and check all the following options.
          required: true
  
  - type: textarea
    attributes: 
      label: Issue with current documentation
      description: |
        Please make sure to leave a reference to the document/ code you're referring to.
        請確保您引用的文件或程式碼的連結可用且能閱覽。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Idea or request for content
      description: |
        Please describe as clearly as possible what topics you think are missing from the current documentation.
        請盡可能清楚地描述目前文檔中缺少哪些主題或哪些內容需要修正。
    validations:
      required: true

  - type: textarea
    id: further_information
    attributes:
      label: Further Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        連結？參考？任何相關資訊都能讓我們更了解您遇到的問題！
      render: shell
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure you the label(s) for what platform you're running(if applicable).
        請確保您已加入該專案所屬的硬體平台的標籤(如果適用)